name: Flux Sync

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - '**'  # Listen for changes in all locations

jobs:
  flux-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config

      - name: Install Flux CLI
        run: curl -s https://fluxcd.io/install.sh | sudo bash

      - name: Reconcile Flux
        run: |
          flux reconcile kustomization flux-system --with-source
